package models

type ContentRes struct {
	ID               string        `json:"id"`
	GroupID          string        `json:"group_id"`
	KnownAs          string        `json:"known_as"`
	Type             int64         `json:"type"`
	Title            string        `json:"title"`
	Ads              []interface{} `json:"ads"`
	CustomAds        string        `json:"custom_ads"`
	EnableAds        int64         `json:"enable_ads"`
	ShortDescription string        `json:"short_description"`
	LongDescription  string        `json:"long_description"`
	Resolution       int64         `json:"resolution"`
	Runtime          int64         `json:"runtime"`
	IsPremium        int64         `json:"is_premium"`
	IsNew            int64         `json:"is_new"`
	IsTrailer        int64         `json:"is_trailer"`
	People           struct {
		Director []struct {
			ID     string `json:"id"`
			Name   string `json:"name"`
			Images struct {
				Avatar string `json:"avatar"`
			} `json:"images"`
			Seo struct {
				Slug        string `json:"slug"`
				URL         string `json:"url"`
				URLRedirect string `json:"url_redirect"`
				ShareURL    string `json:"share_url"`
				Title       string `json:"title"`
				Description string `json:"description"`
			} `json:"seo"`
		} `json:"director"`
		Actor []struct {
			ID     string `json:"id"`
			Name   string `json:"name"`
			Images struct {
				Avatar string `json:"avatar"`
			} `json:"images"`
			Seo struct {
				Slug        string `json:"slug"`
				URL         string `json:"url"`
				URLRedirect string `json:"url_redirect"`
				ShareURL    string `json:"share_url"`
				Title       string `json:"title"`
				Description string `json:"description"`
			} `json:"seo"`
		} `json:"actor"`
	} `json:"people"`
	Tags []struct {
		ID   string `json:"id"`
		Name string `json:"name"`
		Type string `json:"type"`
		Seo  struct {
			Slug        string `json:"slug"`
			URL         string `json:"url"`
			URLRedirect string `json:"url_redirect"`
			ShareURL    string `json:"share_url"`
		} `json:"seo"`
		Slug string `json:"slug"`
	} `json:"tags"`
	ReleaseYear  int64  `json:"release_year"`
	PlayerLogo   string `json:"player_logo"`
	PlayerLogo4K string `json:"player_logo_4k"`
	Images       struct {
		ThumbnailHotV4    string `json:"thumbnail_hot_v4"`
		ThumbnailBigV4    string `json:"thumbnail_big_v4"`
		CarouselTvV4      string `json:"carousel_tv_v4"`
		CarouselAppV4     string `json:"carousel_app_v4"`
		CarouselWebV4     string `json:"carousel_web_v4"`
		ThumbnailV4       string `json:"thumbnail_v4"`
		PosterV4          string `json:"poster_v4"`
		PromotionBanner   string `json:"promotion_banner"`
		TitleCardLight    string `json:"title_card_light"`
		TitleCardDark     string `json:"title_card_dark"`
		PosterOriginal    string `json:"poster_original"`
		ThumbOriginal     string `json:"thumb_original"`
		ThumbnailHotV4Ntc string `json:"thumbnail_hot_v4_ntc"`
		ThumbnailBigV4Ntc string `json:"thumbnail_big_v4_ntc"`
		CarouselTvV4Ntc   string `json:"carousel_tv_v4_ntc"`
		CarouselAppV4Ntc  string `json:"carousel_app_v4_ntc"`
		CarouselWebV4Ntc  string `json:"carousel_web_v4_ntc"`
		ThumbnailV4Ntc    string `json:"thumbnail_v4_ntc"`
		PosterV4Ntc       string `json:"poster_v4_ntc"`
		LivetvLogoLight   string `json:"livetv_logo_light"`
		LivetvLogoDark    string `json:"livetv_logo_dark"`
		LivetvLogoLight11 string `json:"livetv_logo_light_11"`
		LivetvLogoDark11  string `json:"livetv_logo_dark_11"`
		RibbonDetailApp   string `json:"ribbon_detail_app"`
		RibbonDetailWeb   string `json:"ribbon_detail_web"`
		PromotionBannerSm string `json:"promotion_banner_sm"`
		PosterV4Original  string `json:"poster_v4_original"`
		PosterV4Tablet    string `json:"poster_v4_tablet"`
		ThumbnailV4Tablet string `json:"thumbnail_v4_tablet"`
	} `json:"images"`
	AvgRate           float64 `json:"avg_rate"`
	TotalRate         int64   `json:"total_rate"`
	IsWatchlater      bool    `json:"is_watchlater"`
	UserRating        int64   `json:"user_rating"`
	Episode           int64   `json:"episode"`
	CurrentEpisode    string  `json:"current_episode"`
	ContentProviderID string  `json:"content_provider_id"`
	Seo               struct {
		Slug        string `json:"slug"`
		URL         string `json:"url"`
		URLRedirect string `json:"url_redirect"`
		ShareURL    string `json:"share_url"`
	} `json:"seo"`
	Slug           string `json:"slug"`
	SeasonSlugSeo  string `json:"season_slug_seo"`
	IsEnd          bool   `json:"is_end"`
	IsDownloadable int64  `json:"is_downloadable"`
	DefaultEpisode struct {
		ID                string        `json:"id"`
		GroupID           string        `json:"group_id"`
		Type              int           `json:"type"`
		Title             string        `json:"title"`
		Ads               []interface{} `json:"ads"`
		IsPremium         int           `json:"is_premium"`
		IsNew             int           `json:"is_new"`
		ShortDescription  string        `json:"short_description"`
		LongDescription   string        `json:"long_description"`
		Resolution        int           `json:"resolution"`
		Runtime           int           `json:"runtime"`
		Progress          int           `json:"progress"`
		AvgRate           float64       `json:"avg_rate"`
		TotalRate         int           `json:"total_rate"`
		IsWatchlater      bool          `json:"is_watchlater"`
		UserRating        int           `json:"user_rating"`
		Episode           int           `json:"episode"`
		CurrentEpisode    string        `json:"current_episode"`
		ContentProviderID string        `json:"content_provider_id"`
		Seo               struct {
			Slug        string `json:"slug"`
			URL         string `json:"url"`
			URLRedirect string `json:"url_redirect"`
			ShareURL    string `json:"share_url"`
		} `json:"seo"`
		IsEnd    bool `json:"is_end"`
		NoSeeker bool `json:"no_seeker"`
		Images   struct {
			ThumbnailHotV4    string `json:"thumbnail_hot_v4"`
			ThumbnailBigV4    string `json:"thumbnail_big_v4"`
			CarouselTvV4      string `json:"carousel_tv_v4"`
			CarouselAppV4     string `json:"carousel_app_v4"`
			CarouselWebV4     string `json:"carousel_web_v4"`
			ThumbnailV4       string `json:"thumbnail_v4"`
			PosterV4          string `json:"poster_v4"`
			PromotionBanner   string `json:"promotion_banner"`
			TitleCardLight    string `json:"title_card_light"`
			TitleCardDark     string `json:"title_card_dark"`
			PosterOriginal    string `json:"poster_original"`
			ThumbOriginal     string `json:"thumb_original"`
			ThumbnailHotV4Ntc string `json:"thumbnail_hot_v4_ntc"`
			ThumbnailBigV4Ntc string `json:"thumbnail_big_v4_ntc"`
			CarouselTvV4Ntc   string `json:"carousel_tv_v4_ntc"`
			CarouselAppV4Ntc  string `json:"carousel_app_v4_ntc"`
			CarouselWebV4Ntc  string `json:"carousel_web_v4_ntc"`
			ThumbnailV4Ntc    string `json:"thumbnail_v4_ntc"`
			PosterV4Ntc       string `json:"poster_v4_ntc"`
			LivetvLogoLight   string `json:"livetv_logo_light"`
			LivetvLogoDark    string `json:"livetv_logo_dark"`
			LivetvLogoLight11 string `json:"livetv_logo_light_11"`
			LivetvLogoDark11  string `json:"livetv_logo_dark_11"`
			RibbonDetailApp   string `json:"ribbon_detail_app"`
			RibbonDetailWeb   string `json:"ribbon_detail_web"`
			PromotionBannerSm string `json:"promotion_banner_sm"`
			PosterV4Original  string `json:"poster_v4_original"`
			PosterV4Tablet    string `json:"poster_v4_tablet"`
			ThumbnailV4Tablet string `json:"thumbnail_v4_tablet"`
		} `json:"images"`
		RangePageIndex int    `json:"range_page_index"`
		SeoContent     string `json:"seo_content"`
		DrmServiceName string `json:"drm_service_name"`
		IntroStart     int    `json:"intro_start"`
		IntroEnd       int    `json:"intro_end"`
		OuttroStart    int    `json:"outtro_start"`
		OuttroEnd      int    `json:"outtro_end"`
	} `json:"default_episode"`
	Packages       []interface{} `json:"packages"`
	NoSeeker       bool          `json:"no_seeker"`
	GeoCheck       int64         `json:"geo_check"`
	RangePageIndex int64         `json:"range_page_index"`
	Movie          struct {
		Title          string `json:"title"`
		Episode        int    `json:"episode"`
		CurrentEpisode string `json:"current_episode"`
		Seo            struct {
			Slug        string `json:"slug"`
			URL         string `json:"url"`
			URLRedirect string `json:"url_redirect"`
			ShareURL    string `json:"share_url"`
		} `json:"seo"`
		People struct {
			Director interface{} `json:"director"`
			Actor    interface{} `json:"actor"`
		} `json:"people"`
		Tags interface{} `json:"tags"`
	} `json:"movie"`
	DrmServiceName string `json:"drm_service_name"`
	HaveTrailer    int64  `json:"have_trailer"`
	IsVip          int64  `json:"is_vip"`
	IntroStart     int64  `json:"intro_start"`
	IntroEnd       int64  `json:"intro_end"`
	OuttroStart    int64  `json:"outtro_start"`
	OuttroEnd      int64  `json:"outtro_end"`
	Category       int64  `json:"category"`
	VodSchedule    struct {
		Day     string `json:"day"`
		Channel string `json:"channel"`
		Hour    string `json:"hour"`
	} `json:"vod_schedule"`
	SeasonName      string `json:"season_name"`
	ShowName        string `json:"show_name"`
	CreatedAt       int64  `json:"created_at"`
	RatingValue     string `json:"rating_value"`
	AuthorName      string `json:"author_name"`
	ReviewBody      string `json:"review_body"`
	TrailerLinkPlay struct {
		HlsLinkPlay  string `json:"hls_link_play"`
		DashLinkPlay string `json:"dash_link_play"`
	} `json:"trailer_link_play"`
	Metadata struct {
		Award           interface{} `json:"award"`
		LangMetadata    interface{} `json:"lang_metadata"`
		ReleaseType     interface{} `json:"release_type"`
		SubGenres       interface{} `json:"sub_genres"`
		AudioQuality    interface{} `json:"audio_quality"`
		LangOrigin      interface{} `json:"lang_origin"`
		LangOriginTitle interface{} `json:"lang_origin_title"`
		LicenceGeo      interface{} `json:"licence_geo"`
		ReleaseCountry  interface{} `json:"release_country"`
		Supplier        interface{} `json:"supplier"`
	} `json:"metadata"`
	IsComingSoon  int64 `json:"is_coming_soon"`
	RelatedSeason []struct {
		ID             string `json:"id"`
		SeoURL         string `json:"seo_url"`
		Title          string `json:"title"`
		CurrentEpisode string `json:"current_episode"`
		Episode        int64  `json:"episode"`
	} `json:"related_season"`
	AgeRange              string        `json:"age_range"`
	LabelSubtitleAudio    string        `json:"label_subtitle_audio"`
	LabelPublicDay        string        `json:"label_public_day"`
	TagsDisplay           []string      `json:"tags_display"`
	Ranking               int64         `json:"ranking"`
	AwardDescription      string        `json:"award_description"`
	IsPremiumDisplay      string        `json:"is_premium_display"`
	PackageDenyContent    []interface{} `json:"package_deny_content"`
	Status                int64         `json:"status"`
	TrialDuration         int64         `json:"trial_duration"`
	ExpireDate            string        `json:"expire_date"`
	ForceLogin            int64         `json:"force_login"`
	WindowingMessage      string        `json:"windowing_message"`
	TimecodeAds           []interface{} `json:"timecode_ads"`
	IsPremiere            int64         `json:"is_premiere"`
	ButtonLive            string        `json:"button_live"`
	PositionLiveCcu       string        `json:"position_live_ccu"`
	TagsViez              []interface{} `json:"tags_viez"`
	IsSimulcast           int64         `json:"is_simulcast"`
	IsTriggerToApp        int64         `json:"is_trigger_to_app"`
	NumberTrialEpisode    int64         `json:"number_trial_episode"`
	IsTriggerRegister     int64         `json:"is_trigger_register"`
	ShowAotp              int64         `json:"show_aotp"`
	TimeOnTriggerProgress int64         `json:"time_on_trigger_progress"`
	AgeRestricted         bool          `json:"age_restricted"`
	AllowsKid             bool          `json:"allows_kid"`
	HasObjectDetection    bool          `json:"has_object_detection"`
	WarningMessage        string        `json:"warning_message"`
	WarningScreen         string        `json:"warning_screen"`
	WarningTag            string        `json:"warning_tag"`
	CanLimit              bool          `json:"can_limit"`
}
